spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  qr-url-base: ${QR_URL_BASE}
  report:
    recipient-phone-number: ${REPORT_RECIPIENT_PHONE_NUMBER}

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_SECRET_KEY}
    number: ${COOLSMS_SENDER_NUMBER}

external:
  imgbb:
    api:
      key: ${IMGBB_API_KEY}

