spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendant_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 9177
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
